import os
import spotipy
from spotipy.oauth2 import SpotifyOAuth
from flask import Flask, redirect, request, render_template, url_for

app = Flask(__name__)

os.environ['SPOTIPY_CLIENT_ID'] = '4b42bf9b9b864f05b253ec966c07064c'
os.environ['SPOTIPY_CLIENT_SECRET'] = '874c76ed1a4f4aebac8b68814091446f'
os.environ['SPOTIPY_REDIRECT_URI'] = 'http://127.0.0.1:5000/callback'

sp = spotipy.Spotify(auth_manager=SpotifyOAuth(scope='playlist-modify-public'))

@app.route('/')
def index():
    auth_url = sp.auth_manager.get_authorize_url()
    return redirect(auth_url)

@app.route('/callback')
def callback():
    code = request.args.get('code')
    sp.auth_manager.get_access_token(code)
    return redirect(url_for('mood'))

@app.route('/mood', methods=['GET', 'POST'])
def mood():
    if request.method == 'POST':
        mood = request.form['mood']
        return redirect(url_for('create_playlist', mood=mood))
    return render_template('mood.html')

@app.route('/create_playlist/<mood>')
def create_playlist(mood):
    user_id = sp.current_user()['id']
    playlist_name = f"{mood.capitalize()} Playlist"

    # Create a new playlist
    playlist = sp.user_playlist_create(user_id, playlist_name, public=True, description=f"A {mood} playlist generated by the app.")
    playlist_id = playlist['id']

    # Get song recommendations based on mood
    seed_genres = {
        'happy': 'happy',
        'sad': 'sad',
        'energetic': 'party',
        'mellow': 'acoustic',
        'angry': 'heavy'
    }
    recommendations = sp.recommendations(seed_genres=seed_genres[mood], limit=5)

    # Add recommended songs to the playlist
    track_ids = [track['id'] for track in recommendations['tracks']]
    sp.playlist_add_items(playlist_id, track_ids)

    return f'Playlist created! You can view your new playlist <a href="{playlist["external_urls"]["spotify"]}">here</a>.'


if __name__ == '__main__':
    app.run(debug=True)